# Generated by Django 5.2.7 on 2025-10-10 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tutorias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='estado',
            new_name='estado_reserva',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha',
            new_name='fecha_reserva',
        ),
    ]
