# Generated by Django 5.2.7 on 2025-10-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tutorias', '0002_rename_estado_reserva_estado_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
