# Generated by Django 5.2.7 on 2025-10-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tutorias', '0004_curso_modalidad_tutoria_modalidad_tutoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
