# Generated by Django 5.2.7 on 2025-10-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tutorias', '0004_curso_modalidad_tutoria_modalidad_tutoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='ciudad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
