# Generated by Django 5.2.7 on 2025-10-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tutorias', '0005_curso_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='ciudad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
