# Generated by Django 5.2.7 on 2025-11-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tutorias', '0007_usuario_duracion_sesion_minutos_usuario_zona_horaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('tutor', 'Tutor'), ('estudiante', 'Estudiante'), ('admin', 'Administrador')], default='estudiante', max_length=50),
        ),
    ]
