# Generated by Django 5.2.7 on 2025-11-08 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tutorias', '0008_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_propuesta', models.DateField()),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], max_length=50)),
                ('duracion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_reserva', to='gestion_tutorias.curso')),
                ('estudiante', models.ForeignKey(limit_choices_to={'rol': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_reserva', to=settings.AUTH_USER_MODEL)),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='gestion_tutorias.reserva')),
                ('tutoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='gestion_tutorias.tutoria')),
            ],
            options={
                'ordering': ['-creado_en'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'pendiente')), fields=('estudiante', 'curso', 'fecha_propuesta'), name='uniq_solicitud_pendiente_por_fecha')],
            },
        ),
    ]
