# Generated by Django 5.2.7 on 2025-11-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tutorias', '0009_solicitudreserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='unread_estudiante',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='unread_tutor',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
